### PR TITLE
Fixed Camera Permission in Document Scanner

### LINKED ISSUE #1269: Camera permission error in Document Scanner
**Describe the bug**
When opening ImageToolbox for the first time and entering Document Scanner to click "Start Scan," the application does not request camera permissions but instead show "Permission Denial" error.

**To Reproduce**
After a fresh installation of ImageToolbox, directly enter Document Scanner and click the "Start Scan" button.

**Expected behavior**
The application should request camera permissions and display a permission request dialog.

**Screenshots**
5cdebc10c7eeee392da4359010e32de1

**Smartphone (please complete the following information):**
 - Device: Xiaomi 13
 - OS: Hyper OS 1.0.10.0 / Android 14

### PR DESCRIPTION
**Pull request by egmsia01**
Fixes #1269

### CODE REVIEW

**Comment by T8RIN** [comment]
Good, there's also a foss version of the DocumentScanner class, could you include changes to it too please?

**Comment by egmsia01** [comment]
> Good, there's also a foss version of the DocumentScanner class, could you include changes to it too please?

Sure, no problem. However, this is the foss version—I guess you meant the market version(?)

**Comment by T8RIN** [comment]
Oh, I got it, i think the market version handles this internally

**Comment by T8RIN** [comment]
Thanks for the changes!👀 Also feel free to do something by other requests if you want

**Pull request merged**
